stages:
  prepare_data:
    cmd: python src/prepare_data.py
    deps:
      - data/raw
      - config/main.yaml
      - src/prepare_data.py
    outs:
      - data/processed:
          persist: true
  preprocess_data:
    cmd: python src/preprocess_data.py
    deps:
      - data/processed
      - config/main.yaml
      - src/preprocess_data.py
    outs:
      - data/model_input:
          persist: true
  train_clustering:
    cmd: python src/train_clus.py
    deps:
      - data/model_input
      # - data/input_model
      - config/main.yaml
      - src/train_clus.py
    outs:
      - data/output_model:
         persist: true
